package edu.jhu.thrax.util;

public enum MalformedInput
{
    NOT_ENOUGH_FIELDS,
    EMPTY_SOURCE_SENTENCE,
    EMPTY_TARGET_SENTENCE,
    MALFORMED_TARGET_PARSE,
    EMPTY_ALIGNMENT,
    INCONSISTENT_ALIGNMENT,
    UNKNOWN
}

