#!/bin/bash
VERSION="0.80/alpha"

if [[ -z "$THRAX" ]]
then
    THRAX=`dirname $0`
fi

usage () {
    cat <<END_USAGE
Usage: `basename $0` <configuration file> <grammar>
END_USAGE
}

if [[ $# -lt 2 ]]
then
    usage
    exit 1
fi

config=$1
grammar=$2

goal=`$THRAX/lib/getoption.pl $config goal-symbol`
if [[ -z "$goal" ]]
then
    echo "The option 'goal-symbol' was not set in your configuration file." >&2
    echo "Using default goal symbol 'S'." >&2
    goal="S"
fi

features=`$THRAX/lib/getoption.pl $config features`

if [[ file $grammar | grep -q gzip ]]
then
    zcat $grammar | java -cp $THRAX/bin -Xmx500m edu.jhu.thrax.glue.CreateGlueGrammar $goal $features
else
    java -cp $THRAX/bin -Xmx500m edu.jhu.thrax.glue.CreateGlueGrammar $goal $features <$grammar
fi


